version: '3.9'
services:
  master-data:
    build:
      context: .
    image: master-data:latest
    container_name: master_data_app
    ports:
      - 8100:8100
    env_file:
      - ~/remittance/master-data-config.env
    volumes:
      - ~/remittance/master-data:/tmp
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
