---
all:
  vars:
    ansible_connection: network_cli
  hosts:
    dev1:
      ansible_network_os: linux
      ansible_host: 172.16.229.132
      ansible_connection: ssh
      ansible_ssh_user: user
      ansible_ssh_pass: BS-iBank@23#
    dev2:
      ansible_network_os: linux
      ansible_host: 172.16.229.133
      ansible_connection: ssh
      ansible_ssh_user: user
      ansible_ssh_pass: BS-iBank@23#