# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

#    runs-on: ${{matrix.os}}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dipanjalmaitra/master-data:latest

#    - name: Docker Build Master Data Image
#        run: docker build -t dipanjalmaitra/master-data:latest
#    - name: Dockerhub Login
#        env:
#          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#    - name: Docker push
#      run: docker push dipanjalmaitra/master-data:latest

#    - name: Build & push Docker image
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
#        image: dipanjalmaitra/master-data
#        tags: latest
#        registry: docker.io
#        dockerfile: ../Dockerfile
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}


